# Generated by Django 5.1.7 on 2025-04-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
    ]
